In [1]:
import numpy as np
import netCDF4 as nc
import pandas as pd

ModuleNotFoundError: No module named 'netCDF4'

In [2]:
file_path='./qz_ty1_100p.nc'

In [4]:
ds=nc.Dataset(file_path)

In [9]:
ds

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.6
    standard_name_vocabulary: CF-1.6
    featureType: trajectory
    history: Created 2019-03-22 16:30:39.491557
    source: Output from simulation with OpenDrift
    model_url: https://github.com/OpenDrift/opendrift
    opendrift_class: Leeway
    opendrift_module: opendrift.models.leeway
    readers: odict_keys(['E:\\project\\oilspill_rescue\\rescue\\data\\curr\\ecs_curr_20160722_opdr.nc', 'E:\\project\\oilspill_rescue\\rescue\\data\\wind\\nmefc_2016072112_opdr.nc', 'basemap_landmask'])
    time_coverage_start: 2016-07-21 21:00:00
    time_step_calculation: 0:30:00
    time_step_output: 0:30:00
    config_seed:object_type: Person-in-water (PIW), unknown state (mean values)
    config_seed:jibeProbability: 0.04
    config_seed:ocean_only: True
    config_general:use_basemap_landmask: True
    config_general:basemap_resolution: h
    config_general:coastline_action: stranding
 

In [5]:
ds.variables.keys()

odict_keys(['trajectory', 'time', 'status', 'age_seconds', 'lon', 'lat', 'z', 'objectType', 'orientation', 'jibeProbability', 'downwindSlope', 'crosswindSlope', 'downwindOffset', 'crosswindOffset', 'downwindEps', 'crosswindEps', 'x_wind', 'y_wind', 'x_sea_water_velocity', 'y_sea_water_velocity', 'land_binary_mask'])

获取经纬度

In [10]:
ds['lat']

<class 'netCDF4._netCDF4.Variable'>
float32 lat(trajectory, time)
    coordinates: lat lon time
    units: degrees_north
    standard_name: latitude
    long_name: latitude
unlimited dimensions: 
current shape = (100, 25)
filling on, default _FillValue of 9.969209968386869e+36 used

In [11]:
ds['lon']

<class 'netCDF4._netCDF4.Variable'>
float32 lon(trajectory, time)
    coordinates: lat lon time
    units: degrees_east
    standard_name: longitude
    long_name: longitude
unlimited dimensions: 
current shape = (100, 25)
filling on, default _FillValue of 9.969209968386869e+36 used

In [12]:
ds['x_wind']

<class 'netCDF4._netCDF4.Variable'>
float32 x_wind(trajectory, time)
    coordinates: lat lon time
unlimited dimensions: 
current shape = (100, 25)
filling on, default _FillValue of 9.969209968386869e+36 used

---

In [61]:
lat_arr=ds['lat'][:][0]
lat_arr=lat_arr.data
lat_arr

array([ 24.73528862,  24.73561668,  24.73707008,  24.73965454,
        24.74335098,  24.74814987,  24.75413895,  24.76133919,
        24.7696228 ,  24.77903557,  24.78861809,  24.7991066 ,
        24.80935287,  24.81930733,  24.82858086,  24.83700943,
        24.84433365,  24.85040665,  24.85494041,  24.8579483 ,
        24.85980797,  24.86050797,  24.86116219,  24.86176109,  24.86278915], dtype=float32)

In [62]:
lon_arr=ds['lon'][:][0]
lon_arr=lon_arr.data
lon_arr

array([ 118.91770172,  118.92442322,  118.93193817,  118.9402771 ,
        118.94933319,  118.95915222,  118.96904755,  118.97901917,
        118.98840332,  118.99717712,  119.00582886,  119.01359558,
        119.02024841,  119.02571869,  119.03034973,  119.03404236,
        119.03740692,  119.04039764,  119.04359436,  119.04608917,
        119.04959869,  119.05423737,  119.06019592,  119.06761169,
        119.07646179], dtype=float32)

In [64]:
time_arr=ds['time'][:]
time_arr=time_arr.data
time_arr

array([  1.46913480e+09,   1.46913660e+09,   1.46913840e+09,
         1.46914020e+09,   1.46914200e+09,   1.46914380e+09,
         1.46914560e+09,   1.46914740e+09,   1.46914920e+09,
         1.46915100e+09,   1.46915280e+09,   1.46915460e+09,
         1.46915640e+09,   1.46915820e+09,   1.46916000e+09,
         1.46916180e+09,   1.46916360e+09,   1.46916540e+09,
         1.46916720e+09,   1.46916900e+09,   1.46917080e+09,
         1.46917260e+09,   1.46917440e+09,   1.46917620e+09,
         1.46917800e+09])

获取时间

In [15]:
ds['time'][:]

masked_array(data = [  1.46913480e+09   1.46913660e+09   1.46913840e+09   1.46914020e+09
   1.46914200e+09   1.46914380e+09   1.46914560e+09   1.46914740e+09
   1.46914920e+09   1.46915100e+09   1.46915280e+09   1.46915460e+09
   1.46915640e+09   1.46915820e+09   1.46916000e+09   1.46916180e+09
   1.46916360e+09   1.46916540e+09   1.46916720e+09   1.46916900e+09
   1.46917080e+09   1.46917260e+09   1.46917440e+09   1.46917620e+09
   1.46917800e+09],
             mask = False,
       fill_value = 1e+20)

时间戳转换一下

In [65]:
nc.num2date(ds['time'][:],'seconds since 1970-1-1 00:00:00')

array([datetime.datetime(2016, 7, 21, 21, 0),
       datetime.datetime(2016, 7, 21, 21, 30),
       datetime.datetime(2016, 7, 21, 22, 0),
       datetime.datetime(2016, 7, 21, 22, 30),
       datetime.datetime(2016, 7, 21, 23, 0),
       datetime.datetime(2016, 7, 21, 23, 30),
       datetime.datetime(2016, 7, 22, 0, 0),
       datetime.datetime(2016, 7, 22, 0, 30),
       datetime.datetime(2016, 7, 22, 1, 0),
       datetime.datetime(2016, 7, 22, 1, 30),
       datetime.datetime(2016, 7, 22, 2, 0),
       datetime.datetime(2016, 7, 22, 2, 30),
       datetime.datetime(2016, 7, 22, 3, 0),
       datetime.datetime(2016, 7, 22, 3, 30),
       datetime.datetime(2016, 7, 22, 4, 0),
       datetime.datetime(2016, 7, 22, 4, 30),
       datetime.datetime(2016, 7, 22, 5, 0),
       datetime.datetime(2016, 7, 22, 5, 30),
       datetime.datetime(2016, 7, 22, 6, 0),
       datetime.datetime(2016, 7, 22, 6, 30),
       datetime.datetime(2016, 7, 22, 7, 0),
       datetime.datetime(2016, 7, 22, 7

In [6]:
ds['x_wind'][:][0]

masked_array(data=[4.9943113 , 4.819668  , 4.643057  , 4.4523664 ,
                   4.2689314 , 4.0722084 , 3.8735173 , 3.636588  ,
                   3.4052265 , 2.9808044 , 2.5597134 , 2.3360996 ,
                   2.0964293 , 1.695421  , 1.2825478 , 1.0027671 ,
                   0.7237536 , 0.84759426, 0.97972023, 1.099313  ,
                   1.22127   , 1.1062148 , 0.98705584, 0.9541023 ,
                   0.9541023 ],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [8]:
ds['x_wind'][:][1]

masked_array(data=[4.994295 , 4.822786 , 4.64817  , 4.4606676, 4.2798095,
                   4.090003 , 3.8988128, 3.6627917, 3.431748 , 3.0126443,
                   2.5912645, 2.376686 , 2.1493173, 1.7629353, 1.367547 ,
                   1.0965215, 0.8244733, 0.9346679, 1.0528136, 1.1598122,
                   1.2659687, 1.1801863, 1.0875015, 1.0371913, 1.0371913],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [7]:
type(ds['x_wind'][:][0])

numpy.ma.core.MaskedArray

In [23]:
x_wind_arr=ds['x_wind'][:][0].data
x_wind_arr

array([ 4.99431133,  4.81966782,  4.64305687,  4.45236635,  4.26893139,
        4.0722084 ,  3.87351727,  3.6365881 ,  3.40522647,  2.98080444,
        2.55971336,  2.33609962,  2.09642935,  1.69542098,  1.28254783,
        1.00276709,  0.72375357,  0.84759426,  0.97972023,  1.09931302,
        1.22126997,  1.10621476,  0.98705584,  0.95410228,  0.95410228], dtype=float32)

In [43]:
wind_df=pd.DataFrame(x_wind_arr)
wind_df[:5]

0
0  4.994311
1  4.819668
2  4.643057
3  4.452366
4  4.268931

In [45]:
lat_df=pd.DataFrame(lat_arr)
lat_df.head()

0
0  24.735289
1  24.735617
2  24.737070
3  24.739655
4  24.743351

In [46]:
time_df=pd.DataFrame(time_arr)
time_df.head()

0
0  118.917702
1  118.924423
2  118.931938
3  118.940277
4  118.949333

In [42]:
wind_df+lat_df+time_df

0
0   148.647308
1   148.479706
2   148.312073
3   148.132294
4   147.961609
5   147.779510
6   147.596710
7   147.376953
8   147.163254
9   146.757019
10  146.354156
11  146.148804
12  145.926025
13  145.540451
14  145.141479
15  144.873825
16  144.605499
17  144.738403
18  144.878250
19  145.003357
20  145.130676
21  145.020966
22  144.908417
23  144.883469
24  144.893356

In [47]:
[lat_arr,time_arr,x_wind_arr]

[array([ 24.73528862,  24.73561668,  24.73707008,  24.73965454,
         24.74335098,  24.74814987,  24.75413895,  24.76133919,
         24.7696228 ,  24.77903557,  24.78861809,  24.7991066 ,
         24.80935287,  24.81930733,  24.82858086,  24.83700943,
         24.84433365,  24.85040665,  24.85494041,  24.8579483 ,
         24.85980797,  24.86050797,  24.86116219,  24.86176109,  24.86278915], dtype=float32),
 array([ 118.91770172,  118.92442322,  118.93193817,  118.9402771 ,
         118.94933319,  118.95915222,  118.96904755,  118.97901917,
         118.98840332,  118.99717712,  119.00582886,  119.01359558,
         119.02024841,  119.02571869,  119.03034973,  119.03404236,
         119.03740692,  119.04039764,  119.04359436,  119.04608917,
         119.04959869,  119.05423737,  119.06019592,  119.06761169,
         119.07646179], dtype=float32),
 array([ 4.99431133,  4.81966782,  4.64305687,  4.45236635,  4.26893139,
         4.0722084 ,  3.87351727,  3.6365881 ,  3.40522647,  2.9

In [50]:
for x in (lat_arr,time_arr,x_wind_arr):
    print(x)
#     print(y)
#     print(z)
    print('---')

[ 24.73528862  24.73561668  24.73707008  24.73965454  24.74335098
  24.74814987  24.75413895  24.76133919  24.7696228   24.77903557
  24.78861809  24.7991066   24.80935287  24.81930733  24.82858086
  24.83700943  24.84433365  24.85040665  24.85494041  24.8579483
  24.85980797  24.86050797  24.86116219  24.86176109  24.86278915]
---
[ 118.91770172  118.92442322  118.93193817  118.9402771   118.94933319
  118.95915222  118.96904755  118.97901917  118.98840332  118.99717712
  119.00582886  119.01359558  119.02024841  119.02571869  119.03034973
  119.03404236  119.03740692  119.04039764  119.04359436  119.04608917
  119.04959869  119.05423737  119.06019592  119.06761169  119.07646179]
---
[ 4.99431133  4.81966782  4.64305687  4.45236635  4.26893139  4.0722084
  3.87351727  3.6365881   3.40522647  2.98080444  2.55971336  2.33609962
  2.09642935  1.69542098  1.28254783  1.00276709  0.72375357  0.84759426
  0.97972023  1.09931302  1.22126997  1.10621476  0.98705584  0.95410228
  0.95410228]
-

In [56]:
for index in range(len(lat_arr)):
    print(lat_arr[index])
    print(lon_arr[index])
    print(time_arr[index])
    print(x_wind_arr[index])
    print('--')

24.7353
118.918
118.918
4.99431
--
24.7356
118.924
118.924
4.81967
--
24.7371
118.932
118.932
4.64306
--
24.7397
118.94
118.94
4.45237
--
24.7434
118.949
118.949
4.26893
--
24.7481
118.959
118.959
4.07221
--
24.7541
118.969
118.969
3.87352
--
24.7613
118.979
118.979
3.63659
--
24.7696
118.988
118.988
3.40523
--
24.779
118.997
118.997
2.9808
--
24.7886
119.006
119.006
2.55971
--
24.7991
119.014
119.014
2.3361
--
24.8094
119.02
119.02
2.09643
--
24.8193
119.026
119.026
1.69542
--
24.8286
119.03
119.03
1.28255
--
24.837
119.034
119.034
1.00277
--
24.8443
119.037
119.037
0.723754
--
24.8504
119.04
119.04
0.847594
--
24.8549
119.044
119.044
0.97972
--
24.8579
119.046
119.046
1.09931
--
24.8598
119.05
119.05
1.22127
--
24.8605
119.054
119.054
1.10621
--
24.8612
119.06
119.06
0.987056
--
24.8618
119.068
119.068
0.954102
--
24.8628
119.076
119.076
0.954102
--
